import { Bus, Process, root, runtime, build, fixture, coordinator, spawn, stop, call, state, waitState, wait, sleep, assert, equal, denied, key, action, login, dead, kill, run } from './check.js';
const actions = () => Bus.call('org.freedesktop.login1', '/org/freedesktop/login1', 'org.koya.Test.Login', 'Actions');
export default run(async () => {
  let mock = fixture('login');
  await wait(async () => { await login(); return true; });
  let process = coordinator();
  await waitState(s => s.Active && ['wallpaper', 'top-bar'].every(n => s[n + 'Status'] === 'ready'));
  let duplicate = coordinator(); assert(await stopAfterExit(duplicate) !== 0, 'Runtime singleton');
  Process.mkdir(runtime + '/other');
  duplicate = spawn('env', ['XDG_RUNTIME_DIR=' + runtime + '/other', build + '/koya-session-test', root, root + '/tests/fixtures/component.sh']);
  assert(await stopAfterExit(duplicate) !== 0, 'D-Bus singleton');
  await denied(() => call('Ready', 's', 'wallpaper')); await denied(() => call('PowerOff'));
  await denied(() => call('PlatformState', 'a{sv}', { Active: false }));
  await denied(() => call('PlatformButton', 'uu', 116, 1));
  await denied(() => Bus.call('org.koya.Platform1', '/org/koya/Platform1', 'org.koya.Platform1', 'ToggleKeyboard'));
  await key(116, 1); await sleep(100); await key(116, 0); await sleep(1050);
  assert((await state()).PowerMenuState === 'closed', 'Short press opened menu');
  let s = await waitState(s => s.ScreenState === 'off' && s['lock-screenStatus'] === 'ready');
  let lockPid = s['lock-screenPid'];
  await denied(() => call('Unlock')); await denied(() => action('Unlock', 'lock_screen'));
  await key(116, 0); assert((await state()).ScreenState === 'off', 'Unmatched release woke display');
  await key(116, 1); await key(116, 0); s = await state();
  assert(s.ScreenState === 'locked' && s['lock-screenPid'] === lockPid, 'Wake respawned lock');
  await denied(() => call('BeginUnlock', 'u', s.LockGeneration));
  await action('BeginUnlock', 'lock_screen');
  await denied(() => action('BeginUnlock', 'lock_screen'));
  await call('Lock');
  await action('CancelUnlock', 'lock_screen');
  assert((await state()).ScreenState === 'locked', 'Cancelled unlock lost a queued lock');
  await action('Unlock', 'lock_screen'); await waitState(s => s.ScreenState === 'unlocked' && s['lock-screenPid'] === 0);
  await call('Lock'); await waitState(s => s['lock-screenStatus'] === 'ready');
  assert((await state()).ScreenState === 'locked');
  await action('Unlock', 'lock_screen'); await waitState(s => s['lock-screenPid'] === 0);
  await call('Lock'); s = await waitState(s => s['lock-screenStatus'] === 'ready'); lockPid = s['lock-screenPid'];
  await Bus.callComplex('org.koya.Test.lock_screen', '/org/koya/Test/Component', 'org.koya.Test.Component', 'Sequence', 'as', ['Unlock', 'Lock']);
  await sleep(200); s = await state();
  assert(s.ScreenState === 'locked' && s['lock-screenPid'] === lockPid, 'Relock replaced owned process');
  await key(116, 1); await key(116, 0); assert((await state()).ScreenState === 'off');
  await key(116, 1); await waitState(s => s.PowerMenuState === 'open'); await key(116, 0);
  assert((await state()).ScreenState === 'locked', 'Long press release powered off');
  await call('DismissPowerMenu'); await waitState(s => s.PowerMenuState === 'closed');
  await action('Unlock', 'lock_screen'); await waitState(s => s['lock-screenPid'] === 0);
  await key(116, 1); await Bus.call('org.koya.Shell1', '/org/koya/Shell1', 'org.koya.Shell1.Test', 'DeviceLost'); await sleep(1050);
  assert((await state()).PowerMenuState === 'closed', 'Removed device completed hold');
  await key(116, 1); await login(false); await waitState(s => !s.Active); await sleep(1050);
  assert((await state()).PowerMenuState === 'closed'); await denied(() => call('ShowPowerMenu'));
  await login(); await waitState(s => s.Active);
  await key(116, 1); await sleep(500); await key(116, 2); assert((await state()).PowerMenuState === 'closed');
  s = await waitState(s => s.PowerMenuState === 'open'); const menuPid = s['power-menuPid'];
  await key(116, 2); await call('ShowPowerMenu'); assert((await state())['power-menuPid'] === menuPid);
  await call('DismissPowerMenu'); await waitState(s => s.PowerMenuState === 'closed');
  await key(116, 2); await sleep(1050); assert((await state()).PowerMenuState === 'closed', 'Repeat retriggered hold');
  await key(116, 0); assert((await state()).ScreenState === 'unlocked');
  const events = [];
  Bus.addMatch("type='signal',interface='org.koya.Shell1',member='HardwareButton'");
  const collect = sig => { if (sig.member === 'HardwareButton') events.push(sig.args[0]); };
  Bus.onSignal(collect); await call('GetState');
  for (const value of [1, 2, 0]) await key(115, value);
  await wait(() => events.length === 3);
  equal(events, ['pressed', 'repeat', 'released'].map(State => ({Button: 'volume-up', State})));
  Bus.offSignal(collect);
  await key(116, 1); await stop(mock); await waitState(s => !s.Active); await sleep(1050);
  assert((await state()).PowerMenuState === 'closed');
  mock = fixture('login'); await waitState(s => s.Active);
  await call('ShowPowerMenu'); await waitState(s => s.PowerMenuState === 'open');
  await login(true, 'challenge'); await denied(() => action('PowerOff')); assert((await state()).PowerMenuState === 'open');
  equal(await Bus.call('org.freedesktop.login1', '/org/freedesktop/login1', 'org.koya.Test.Login', 'Attempts'), ['PowerOff:true']);
  await login(true, 'yes', true); await denied(() => action('Reboot')); assert((await state()).LastError.includes('Test inhibitor'));
  await login(); await action('Reboot'); assert((await state()).PowerMenuState === 'pending'); await denied(() => action('PowerOff'));
  equal(await actions(), ['Reboot']);
  s = await state(); let pids = ['wallpaper', 'top-bar', 'power-menu'].map(n => s[n + 'Pid']);
  assert(await stop(process) === 0); await wait(async () => (await Promise.all(pids.map(dead))).every(Boolean));
  process = coordinator(); await waitState(s => s['top-barStatus'] === 'ready');
  await call('ShowPowerMenu'); await waitState(s => s.PowerMenuState === 'open'); await action('PowerOff');
  equal(await actions(), ['Reboot', 'PowerOff']);
  for (let attempt = 0; attempt < 4; attempt++) {
    const old = (await state())['top-barPid']; assert(old > 1); await kill(old);
    await waitState(s => attempt < 3 ? s['top-barStatus'] === 'ready' && s['top-barPid'] > 1 && s['top-barPid'] !== old : s['top-barStatus'] === 'failed');
  }
  s = await state(); pids = ['wallpaper', 'power-menu'].map(n => s[n + 'Pid']);
  await stop(process, 9); await wait(async () => (await Promise.all(pids.map(dead))).every(Boolean));
  process = coordinator(); s = await waitState(s => s['top-barStatus'] === 'ready' && s.authenticationStatus === 'ready');
  pids = ['wallpaper', 'top-bar', 'authentication'].map(n => s[n + 'Pid']);
  await kill(s.platformPid);
  await wait(() => process.code !== null, 'Platform failure did not stop the shell');
  await wait(async () => (await Promise.all(pids.map(dead))).every(Boolean), 'UI survived platform failure');
});
async function stopAfterExit(child) { await wait(() => child.code !== null, 'Duplicate did not exit'); return child.code; }
